#!/usr/bin/env bash
# =============================================================================
# assemble_ab_disk.sh — RK3588 A/B-virt emulator: 2-slot GPT disk assembler (PWU-AB-1)
# -----------------------------------------------------------------------------
# Purpose:
#   Take the built guest artifacts (kernel Image + rootfs.ext2 + u-boot.bin) and
#   assemble a deterministic 2-slot (A/B) GPT disk image `ab_disk.img` that the
#   U-Boot A/B boot script (uboot_ab/boot.cmd -> boot.scr) selects + rolls back
#   between. This is the disk PWU-AB-1 boots under QEMU `-machine virt` + HVF to
#   prove a REAL slot switch on this Apple-Silicon host
#   (docs/research/rk3588_emulator/REPORT.md §3, PWU-AB-1).
#
#   GPT layout produced (MUST match uboot_ab/boot.cmd + uboot_ab/README.md):
#     p1  FAT      boot       — kernel Image + boot.scr      (U-Boot: virtio 0:1)
#     p2  ext2/4   rootfs_a   — slot A root (seeded from rootfs.ext2)  -> /dev/vda2
#     p3  ext2/4   rootfs_b   — slot B root (distinct copy, /etc/slot_id=B) -> /dev/vda3
#   Slot B carries a recognizable marker `/etc/slot_id=B` (slot A gets
#   `/etc/slot_id=A`) so a slot switch is OBSERVABLE from inside the guest:
#   `findmnt /` + `cat /etc/slot_id` proves which physical partition is root.
#
#   boot.scr is compiled here from uboot_ab/boot.cmd via:
#     mkimage -A arm64 -O linux -T script -C none -d boot.cmd boot.scr
#
# Why a container (FACT): this host is macOS; sgdisk/sfdisk/mke2fs/mkfs.fat/
#   debugfs/mkimage + GPT loop assembly need a Linux toolchain. The assembly runs
#   INSIDE a NAMED podman aarch64 Linux container (native arm64, no emulation),
#   exactly like build_image.sh.
#
# macOS/podman portability (FACT — the rules that broke earlier builds):
#   * NO /Volumes bind-mount (the project lives on an external volume NOT shared
#     into the podman machine VM). Inputs are copied IN via `podman cp`; the
#     finished disk is copied OUT via `podman cp`.
#   * NO `:Z` SELinux relabel (macOS podman rejects it).
#   * NO apostrophes or parens inside the single-quoted `podman ... bash -c '...'`
#     string (that exact lexical bug broke earlier builds). The in-container
#     script below is ASCII-safe: no `'`, no `(`/`)`.
#   * The container is `podman rm -f`'d on every entry + exit path.
#
# Usage:
#   tests/emulator/ab_virt/assemble_ab_disk.sh            # assemble ab_disk.img
#   tests/emulator/ab_virt/assemble_ab_disk.sh --clean    # also wipe prior img + ctr
#   Env: HELIX_AB_DISK_MB (total disk MB, default 1024)
#        HELIX_AB_BOOT_MB (FAT boot partition MB, default 64)
#
# Inputs (produced by build_image.sh; same out/ tree):
#   tests/emulator/ab_virt/out/images/{Image,rootfs.ext2,u-boot.bin}
# Outputs (gitignored, §11.4.30/§11.4.77 — regenerated by this script):
#   tests/emulator/ab_virt/out/images/ab_disk.img   (the 2-slot GPT disk)
#   tests/emulator/ab_virt/out/images/boot.scr      (compiled U-Boot script)
#   tests/emulator/ab_virt/out/assemble.log         (full transcript)
#   tests/emulator/ab_virt/out/.disk_ok             (stamp — ONLY on real success)
#
# Side-effects: creates/removes a named podman container + writes under out/.
# Dependencies: podman (aarch64 Linux container); the guest artifacts above.
# Cross-references: uboot_ab/boot.cmd + uboot_ab/README.md (the coherence
#   contract), build_image.sh (input producer), REPORT.md §3/§4/PWU-AB-1,
#   §11.4.6 (only stamp .disk_ok if ab_disk.img exists non-empty),
#   §11.4.67 (sh -n + bash -n clean), §11.4.74/§11.4.76 (reuse + container).
# =============================================================================
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${SCRIPT_DIR}/out"
IMG_DIR="${OUT}/images"
UBOOT_DIR="${SCRIPT_DIR}/uboot_ab"
DISK_MB="${HELIX_AB_DISK_MB:-1024}"
BOOT_MB="${HELIX_AB_BOOT_MB:-64}"
ASM_CTR="helix_ab_assemble"

log() { printf '[assemble_ab_disk %s] %s\n' "$(date -u +%H:%M:%S)" "$*"; }

command -v podman >/dev/null 2>&1 || { log "ABORT: podman not found"; exit 3; }

# ---- preconditions: real inputs must exist (no phantom assembly) -------------
[ -s "${IMG_DIR}/Image" ]       || { log "ABORT: ${IMG_DIR}/Image missing — run build_image.sh first"; exit 3; }
[ -s "${IMG_DIR}/rootfs.ext2" ] || { log "ABORT: ${IMG_DIR}/rootfs.ext2 missing — run build_image.sh first"; exit 3; }
[ -s "${IMG_DIR}/u-boot.bin" ]  || { log "ABORT: ${IMG_DIR}/u-boot.bin missing — u-boot.bin still building (PWU-AB-1 needs the real bootloader)"; exit 3; }
[ -f "${UBOOT_DIR}/boot.cmd" ]  || { log "ABORT: ${UBOOT_DIR}/boot.cmd missing"; exit 3; }

if [ "${1:-}" = "--clean" ]; then
  log "cleaning prior disk image + stale assemble container"
  rm -f "${IMG_DIR}/ab_disk.img" "${IMG_DIR}/boot.scr" "${OUT}/.disk_ok"
  podman rm -f "$ASM_CTR" >/dev/null 2>&1 || true
fi
rm -f "${OUT}/.disk_ok"
mkdir -p "$IMG_DIR"

podman rm -f "$ASM_CTR" >/dev/null 2>&1 || true

log "assembling 2-slot GPT disk in named container '${ASM_CTR}' (disk=${DISK_MB}MB boot=${BOOT_MB}MB) ..."

# Start a long-lived named container we copy inputs INTO, run the assembly IN,
# then copy the disk OUT of. No bind-mount, no :Z.
podman run -d --name "$ASM_CTR" --arch arm64 \
  docker.io/library/debian:bookworm-slim sleep 600 \
  >"${OUT}/assemble.log" 2>&1 \
  || { log "ABORT: could not start assemble container"; tail -5 "${OUT}/assemble.log"; exit 1; }

cleanup() { podman rm -f "$ASM_CTR" >/dev/null 2>&1 || true; }
trap cleanup EXIT

# Copy inputs into the container workdir /asm.
podman exec "$ASM_CTR" mkdir -p /asm/in >>"${OUT}/assemble.log" 2>&1
podman cp "${IMG_DIR}/Image"        "${ASM_CTR}:/asm/in/Image"        >>"${OUT}/assemble.log" 2>&1
podman cp "${IMG_DIR}/rootfs.ext2"  "${ASM_CTR}:/asm/in/rootfs.ext2"  >>"${OUT}/assemble.log" 2>&1
podman cp "${IMG_DIR}/u-boot.bin"   "${ASM_CTR}:/asm/in/u-boot.bin"   >>"${OUT}/assemble.log" 2>&1
podman cp "${UBOOT_DIR}/boot.cmd"   "${ASM_CTR}:/asm/in/boot.cmd"     >>"${OUT}/assemble.log" 2>&1

# -----------------------------------------------------------------------------
# In-container assembly. CRITICAL (the bug that broke earlier builds):
#   this whole script is a SINGLE-QUOTED podman bash -c string, so it MUST stay
#   ASCII-safe: NO apostrophes, NO parens anywhere inside it. Use printf with
#   plain words, here-strings avoided, comments use dashes not parens.
# Layout numbers are passed via -e env so the quoted string contains no shell
# substitution of host vars.
# -----------------------------------------------------------------------------
podman exec -e DISK_MB="$DISK_MB" -e BOOT_MB="$BOOT_MB" "$ASM_CTR" \
  bash -euo pipefail -c '
    export DEBIAN_FRONTEND=noninteractive
    apt-get -qq update >/dev/null
    apt-get -qq install -y --no-install-recommends \
      gdisk dosfstools e2fsprogs mtools u-boot-tools fdisk util-linux \
      >/dev/null
    cd /asm

    # ---- compile boot.cmd -> boot.scr -----------------------------------
    mkimage -A arm64 -O linux -T script -C none -d in/boot.cmd in/boot.scr
    test -s in/boot.scr || { echo ASM_FAIL: boot.scr not produced; exit 11; }

    # ---- sizing in MiB --------------------------------------------------
    ROOT_SRC_BYTES=$(stat -c %s in/rootfs.ext2)
    ROOT_SRC_MB=$(( ROOT_SRC_BYTES / 1048576 + 1 ))
    # Each slot gets the rootfs size plus 32 MiB headroom for the marker write.
    SLOT_MB=$(( ROOT_SRC_MB + 32 ))
    NEEDED_MB=$(( BOOT_MB + SLOT_MB + SLOT_MB + 8 ))
    if [ "$DISK_MB" -lt "$NEEDED_MB" ]; then
      echo ASM_NOTE: requested disk ${DISK_MB}MB too small, bumping to ${NEEDED_MB}MB
      DISK_MB=$NEEDED_MB
    fi
    echo ASM: disk=${DISK_MB}MB boot=${BOOT_MB}MB slot=${SLOT_MB}MB rootfs_src=${ROOT_SRC_MB}MB

    # ---- create the raw disk + GPT --------------------------------------
    rm -f out_ab_disk.img
    truncate -s ${DISK_MB}M out_ab_disk.img

    # Deterministic GPT: p1 boot FAT, p2 rootfs_a, p3 rootfs_b.
    # sgdisk sizes: +<MB>M for fixed parts, 0 = rest of disk for the last.
    sgdisk --clear \
      -n 1:0:+${BOOT_MB}M  -t 1:0700 -c 1:boot \
      -n 2:0:+${SLOT_MB}M  -t 2:8300 -c 2:rootfs_a \
      -n 3:0:0             -t 3:8300 -c 3:rootfs_b \
      out_ab_disk.img
    sgdisk -p out_ab_disk.img

    # ---- read partition byte offsets/sizes from the GPT -----------------
    # sfdisk -d prints start+size in 512-byte sectors per partition line.
    SECT=512
    P1_START=$(sfdisk -d out_ab_disk.img | sed -n "s#.*out_ab_disk.img1 : start= *\([0-9]*\).*#\1#p")
    P1_SIZE=$(sfdisk  -d out_ab_disk.img | sed -n "s#.*out_ab_disk.img1 :.*size= *\([0-9]*\).*#\1#p")
    P2_START=$(sfdisk -d out_ab_disk.img | sed -n "s#.*out_ab_disk.img2 : start= *\([0-9]*\).*#\1#p")
    P2_SIZE=$(sfdisk  -d out_ab_disk.img | sed -n "s#.*out_ab_disk.img2 :.*size= *\([0-9]*\).*#\1#p")
    P3_START=$(sfdisk -d out_ab_disk.img | sed -n "s#.*out_ab_disk.img3 : start= *\([0-9]*\).*#\1#p")
    P3_SIZE=$(sfdisk  -d out_ab_disk.img | sed -n "s#.*out_ab_disk.img3 :.*size= *\([0-9]*\).*#\1#p")
    echo ASM: p1 start=$P1_START size=$P1_SIZE  p2 start=$P2_START size=$P2_SIZE  p3 start=$P3_START size=$P3_SIZE
    test -n "$P1_START" -a -n "$P2_START" -a -n "$P3_START" || { echo ASM_FAIL: could not read GPT offsets; exit 12; }

    # ---- build the FAT boot partition image: Image + boot.scr -----------
    P1_BYTES=$(( P1_SIZE * SECT ))
    rm -f boot.part
    truncate -s ${P1_BYTES} boot.part
    mkfs.fat -F 32 -n BOOT boot.part >/dev/null
    mcopy -i boot.part in/Image    ::Image
    mcopy -i boot.part in/boot.scr ::boot.scr
    mdir -i boot.part ::

    # ---- prepare slot A rootfs: copy rootfs.ext2 + tag /etc/slot_id=A ----
    cp in/rootfs.ext2 rootfs_a.img
    P2_BYTES=$(( P2_SIZE * SECT ))
    # Grow the slot image to fill the partition so resize is unnecessary in-guest.
    truncate -s ${P2_BYTES} rootfs_a.img
    e2fsck -fy rootfs_a.img >/dev/null 2>&1 || true
    resize2fs rootfs_a.img >/dev/null 2>&1 || true
    printf "A\n" > slot_a.txt
    printf "cd /etc\nrm slot_id\nwrite slot_a.txt slot_id\n" | debugfs -w rootfs_a.img >/dev/null 2>&1 || \
      printf "cd /etc\nwrite slot_a.txt slot_id\n" | debugfs -w rootfs_a.img >/dev/null 2>&1
    echo ASM: slot A /etc/slot_id check:
    printf "cat /etc/slot_id\n" | debugfs rootfs_a.img 2>/dev/null | tail -1

    # ---- prepare slot B rootfs: distinct copy + tag /etc/slot_id=B ------
    cp in/rootfs.ext2 rootfs_b.img
    P3_BYTES=$(( P3_SIZE * SECT ))
    truncate -s ${P3_BYTES} rootfs_b.img
    e2fsck -fy rootfs_b.img >/dev/null 2>&1 || true
    resize2fs rootfs_b.img >/dev/null 2>&1 || true
    printf "B\n" > slot_b.txt
    printf "cd /etc\nrm slot_id\nwrite slot_b.txt slot_id\n" | debugfs -w rootfs_b.img >/dev/null 2>&1 || \
      printf "cd /etc\nwrite slot_b.txt slot_id\n" | debugfs -w rootfs_b.img >/dev/null 2>&1
    echo ASM: slot B /etc/slot_id check:
    printf "cat /etc/slot_id\n" | debugfs rootfs_b.img 2>/dev/null | tail -1

    # ---- splice the three partition images into the GPT disk ------------
    dd if=boot.part    of=out_ab_disk.img bs=$SECT seek=$P1_START conv=notrunc status=none
    dd if=rootfs_a.img of=out_ab_disk.img bs=$SECT seek=$P2_START conv=notrunc status=none
    dd if=rootfs_b.img of=out_ab_disk.img bs=$SECT seek=$P3_START conv=notrunc status=none

    sync
    echo ASM: final GPT:
    sgdisk -p out_ab_disk.img
    ls -la out_ab_disk.img in/boot.scr
    echo ASM_OK
  ' >>"${OUT}/assemble.log" 2>&1
RC=$?

if [ "$RC" -ne 0 ] || ! grep -q '^ASM_OK$' "${OUT}/assemble.log"; then
  log "ASSEMBLY FAILED (rc=$RC) — see out/assemble.log (tail):"; tail -30 "${OUT}/assemble.log" 2>/dev/null
  exit 1
fi

# ---- copy the finished disk + boot.scr OUT via podman cp --------------------
log "extracting ab_disk.img + boot.scr via podman cp ..."
podman cp "${ASM_CTR}:/asm/out_ab_disk.img" "${IMG_DIR}/ab_disk.img" >>"${OUT}/assemble.log" 2>&1
podman cp "${ASM_CTR}:/asm/in/boot.scr"     "${IMG_DIR}/boot.scr"    >>"${OUT}/assemble.log" 2>&1

# §11.4.6: declare success ONLY if the real disk image is present + non-empty.
if [ -s "${IMG_DIR}/ab_disk.img" ]; then
  printf 'disk_mb=%s boot_mb=%s built=%s\n' "$DISK_MB" "$BOOT_MB" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "${OUT}/.disk_ok"
  log "ASSEMBLY OK — 2-slot GPT disk produced:"; ls -la "${IMG_DIR}/ab_disk.img" "${IMG_DIR}/boot.scr" 2>/dev/null
  exit 0
fi
log "ASSEMBLY finished but ab_disk.img missing — NOT stamping .disk_ok (anti-bluff §11.4.6)"
exit 1
