#!/usr/bin/env bash
# =============================================================================
# Generate Stats Report — Human-readable report from docs/Stats.tsv
# -----------------------------------------------------------------------------
# Purpose: Reads docs/Stats.tsv (the per-build summary registry) and renders
#          docs/Stats.md — a markdown report with ever-values (min/max/mean
#          across all tracked builds) and per-build entries sorted most-recent-
#          first.  Auto-invoked by resource_sampler.sh on stop.
#
# Usage:
#   bash scripts/generate_stats_report.sh
#
# Inputs:
#   docs/Stats.tsv  — Tab-separated registry with header row:
#       label | timestamp | memory_min | memory_max | memory_mean | memory_p95
#       | cpu_min | cpu_max | cpu_mean | cpu_p95 | status
#
# Outputs:
#   docs/Stats.md   — Markdown report with §11.4.44 revision header, ever-values
#                     table, and per-build entries.
#
# Side-effects:
#   - Overwrites docs/Stats.md
#
# Dependencies:
#   awk(1), printf(1), date(1)
#
# Cross-references:
#   §11.4.24 — Build-resource stats tracking mandate
#   §11.4.44 — Document revision header mandate
#   scripts/resource_sampler.sh — Sampler that feeds this report
#   docs/Stats.tsv — Registry (input)
#   docs/Stats.md — Report (output)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REGISTRY="${PROJECT_ROOT}/docs/Stats.tsv"
REPORT="${PROJECT_ROOT}/docs/Stats.md"

if [ ! -f "${REGISTRY}" ]; then
    echo "WARNING: ${REGISTRY} not found — creating empty Stats.md" >&2
    cat > "${REPORT}" <<'EOF'
# Build Resource Stats

**Revision:** 1
**Last modified:** 1970-01-01T00:00:00Z
**Source:** §11.4.24 Build-resource stats tracker

_No builds tracked yet._

---
*Generated by resource_sampler at 1970-01-01T00:00:00Z*
EOF
    exit 0
fi

# Count data rows (exclude header)
ROW_COUNT="$(awk 'NR>1 && NF>0' "${REGISTRY}" | wc -l | tr -d ' ')"

if [ "${ROW_COUNT}" -eq 0 ]; then
    cat > "${REPORT}" <<'EOF'
# Build Resource Stats

**Revision:** 1
**Last modified:** 1970-01-01T00:00:00Z
**Source:** §11.4.24 Build-resource stats tracker

_No builds tracked yet._

---
*Generated by resource_sampler at 1970-01-01T00:00:00Z*
EOF
    exit 0
fi

# ─── compute ever-values ─────────────────────────────────────────────────────

# Memory (columns 3-6: memory_min, memory_max, memory_mean, memory_p95)
EV_MEM_MIN="$(awk 'NR>1 && $3!="" {if(!min) min=$3; if($3<min) min=$3} END{printf "%.1f", min}' "${REGISTRY}")"
EV_MEM_MAX="$(awk 'NR>1 && $4!="" {if(!max) max=$4; if($4>max) max=$4} END{printf "%.1f", max}' "${REGISTRY}")"
EV_MEM_MEAN="$(awk 'NR>1 && $5!="" {sum+=$5; n++} END{if(n>0) printf "%.1f", sum/n; else print "0.0"}' "${REGISTRY}")"

# CPU (columns 7-10: cpu_min, cpu_max, cpu_mean, cpu_p95)
EV_CPU_MIN="$(awk 'NR>1 && $7!="" {if(!min) min=$7; if($7<min) min=$7} END{printf "%.1f", min}' "${REGISTRY}")"
EV_CPU_MAX="$(awk 'NR>1 && $8!="" {if(!max) max=$8; if($8>max) max=$8} END{printf "%.1f", max}' "${REGISTRY}")"
EV_CPU_MEAN="$(awk 'NR>1 && $9!="" {sum+=$9; n++} END{if(n>0) printf "%.1f", sum/n; else print "0.0"}' "${REGISTRY}")"

# ─── per-build rows (most-recent-first) ──────────────────────────────────────

BUILD_ROWS=""
# Read TSV from tail to produce most-recent-first
BUILD_ROWS="$(awk -F'\t' '
NR>1 && NF>=11 {
    label=$1
    ts=$2
    mem_min=$3; mem_max=$4; mem_mean=$5; mem_p95=$6
    cpu_min=$7; cpu_max=$8; cpu_mean=$9; cpu_p95=$10
    status=$11
    printf "| %s | %s | %s | %s/%s/%s MB | %s/%s/%s %% | %s | %s |\n", \
        label, ts, status, \
        mem_min, mem_max, mem_mean, \
        cpu_min, cpu_max, cpu_mean, \
        "-", status
}
' "${REGISTRY}" | sort -t'|' -k2 -r)"  # sort by timestamp descending

# ─── reassemble into per-build table ─────────────────────────────────────────

# Build per-build rows with proper format
PER_BUILD=""
while IFS= read -r line; do
    PER_BUILD="${PER_BUILD}${line}"$'\n'
done < <(awk -F'\t' '
NR>1 && NF>=11 {
    label=$1; ts=$2; status=$11
    mem_min=$3; mem_max=$4; mem_mean=$5; mem_p95=$6
    cpu_min=$7; cpu_max=$8; cpu_mean=$9; cpu_p95=$10

    printf "| %s | %s | %s | %s/%s/%s | %s/%s/%s | %s | %s |\n", \
        label, ts, status, \
        mem_min, mem_max, mem_mean, \
        cpu_min, cpu_max, cpu_mean, \
        "-", "-"
}' "${REGISTRY}" | sort -t'|' -k2 -r)

NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

cat > "${REPORT}" <<REPORT_EOF
# Build Resource Stats

**Revision:** 1
**Last modified:** ${NOW}
**Source:** §11.4.24 Build-resource stats tracker

## Ever-values (across all tracked builds)

| Metric | Min | Max | Mean |
|--------|-----|-----|------|
| Memory (MB) | ${EV_MEM_MIN} | ${EV_MEM_MAX} | ${EV_MEM_MEAN} |
| CPU % | ${EV_CPU_MIN} | ${EV_CPU_MAX} | ${EV_CPU_MEAN} |
| Load | - | - | - |
| Disk Read (blocks/sample) | - | - | - |
| Disk Write (blocks/sample) | - | - | - |

## Per-build

| Build ID | Timestamp | Status | Memory (MB) | CPU % | Disk R | Disk W |
|----------|-----------|--------|-------------|-------|--------|--------|
${PER_BUILD}---
*Generated by resource_sampler at ${NOW}*
REPORT_EOF

echo "Report generated: ${REPORT}"
